apiVersion: v1
kind: Service
metadata:
  name: access-grafana
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- end }}
