{
 "title": "Rancher Session Servers",
 "tags": [ "rancher" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "All WS Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(session_server_total_add_websocket_session) - (count(session_server_total_remove_websocket_session) or on () vector(0))"
    }
   ]
  },
  {
   "title": "InActive WS Session",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(session_server_total_add_websocket_session) by (clientkey) - sum(session_server_total_remove_websocket_session) by (clientkey)==0)"
    }
   ]
  },
  {
   "title": "Active Peering WebSocket Session",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((count(session_server_total_add_websocket_session{peer=\"true\"}  -  session_server_total_remove_websocket_session{peer=\"true\"} > 0)) or (absent(sum(nonexistent{job=\"dummy\"})) - 1))  + count(session_server_total_add_websocket_session{peer=\"true\"}) - (count(session_server_total_remove_websocket_session{peer=\"true\"}) or (absent(sum(nonexistent{job=\"dummy\"}))-1)) "
    }
   ]
  },
  {
   "title": "Active Node Agent WS Session",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(sum(session_server_total_add_websocket_session{clientkey=~\".*m-.*|.*machine-.*\"}) by (clientkey) - sum(session_server_total_remove_websocket_session{clientkey=~\".*m-.*|.*machine-.*\"}) by (clientkey) > 0) or on() vector(0)) + count(sum(session_server_total_add_websocket_session{clientkey=~\".*m-.*|.*machine-.*\"}) by (clientkey)) - (count(sum(session_server_total_remove_websocket_session{clientkey=~\".*m-.*|.*machine-.*\"}) by (clientkey)) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Active Cluster Agent WS Session",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(sum(session_server_total_add_websocket_session{clientkey=~\"c-[a-z0-9]{5}|local\"}) by (clientkey)  -  sum(session_server_total_remove_websocket_session{clientkey=~\"c-[a-z0-9]{5}|local\"}) by (clientkey) > 0) or on() vector(0)) + count(sum(session_server_total_add_websocket_session{clientkey=~\"c-[a-z0-9]{5}|local\"}) by (clientkey)) - (count(sum(session_server_total_remove_websocket_session{clientkey=~\"c-[a-z0-9]{5}|local\"}) by (clientkey)) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(session_server_total_add_connections) by (clientkey, addr) - (sum(session_server_total_remove_connections) by (clientkey, addr) or on() vector(0)))"
    }
   ]
  },
  {
   "title": "Number of In-Flight Connection",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_server_total_add_connections - session_server_total_remove_connections)"
    }
   ]
  },
  {
   "title": "Transmit over WS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(session_server_total_transmit_bytes[2m])) + sum(rate(session_server_total_transmit_error_bytes[2m]))"
    }
   ]
  },
  {
   "title": "Receive over WS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(session_server_total_receive_bytes[2m])) "
    }
   ]
  },
  {
   "title": "The number of add/remove WS seesion last 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(session_server_total_add_websocket_session[5m]) > 0",
     "legendFormat": "Add {{ clientkey }} "
    },
    {
     "expr": " - increase(session_server_total_remove_websocket_session[5m]) < 0",
     "legendFormat": "Remove {{ clientkey }} "
    }
   ]
  },
  {
   "title": "InActive WS Session",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "session_server_total_add_websocket_session - session_server_total_remove_websocket_session < 1",
     "legendFormat": "{{ clientkey }} "
    }
   ]
  },
  {
   "title": "In-Flight Connection over WS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "session_server_total_add_connections - session_server_total_remove_connections > 0",
     "legendFormat": "{{ clientkey }} -> {{ addr }}"
    }
   ]
  },
  {
   "title": "Number of Connection over WS (TOP15)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, increase(session_server_total_add_connections[5m]))",
     "legendFormat": "{{ clientkey }} -> {{ addr }}"
    }
   ]
  },
  {
   "title": "Transmit bytes over remotedialer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(session_server_total_transmit_bytes[5m])",
     "legendFormat": "{{ clientkey }} "
    }
   ]
  },
  {
   "title": "Transmit Error bytes over remotedialer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(session_server_total_transmit_error_bytes[5m])",
     "legendFormat": "{{ clientkey }} "
    }
   ]
  },
  {
   "title": "Receive bytes over remotedialer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(session_server_total_receive_bytes[5m])",
     "legendFormat": "{{ clientkey }} "
    }
   ]
  }
 ]
}