global:
  cattle:
    systemDefaultRegistry: ""
    psp:
      enabled: true

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.11.0

kubectl:
  image:
    repository: rancher/kubectl
    tag: v1.23.3
