apiVersion: v1
kind: Service
metadata:
  name: access-thanos
  labels:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: query
    kubernetes.io/cluster-service: "true"
spec:
  type: {{ .Values.thanos.query.service.type }}
  ports:
    - port: {{ .Values.thanos.query.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
      {{- if (eq .Values.thanos.query.service.type "ClusterIP") }}
      nodePort: null
      {{- end }}
  selector:
    app: {{ template "app.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: query
---
{{- if .Values.clusterIds }}
{{- range $clusterId := (split ":" .Values.clusterIds) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $clusterId }}
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: {{ template "app.fullname" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    component: query
---
{{- end }}
{{- end }}
