{{- if and .Release.IsInstall .Values.global.installCRDs -}}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/Alertmanager") }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- else }}
apiVersion: apiextensions.k8s.io/v1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: {{ printf "alertmanagers.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  annotations:
    "helm.sh/hook": crd-install
{{- end }}
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: Alertmanager
    plural: alertmanagers
  scope: Namespaced
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  version: v1
{{- else }}
  versions:
  - name: v1
    served: false
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
{{- end }}
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/Prometheus") }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- else }}
apiVersion: apiextensions.k8s.io/v1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: {{ printf "prometheuses.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  annotations:
    "helm.sh/hook": crd-install
{{- end }}
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: Prometheus
    plural: prometheuses
  scope: Namespaced
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  version: v1
{{- else }}
  versions:
  - name: v1
    served: false
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
{{- end }}
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule") }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- else }}
apiVersion: apiextensions.k8s.io/v1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: {{ printf "prometheusrules.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  annotations:
    "helm.sh/hook": crd-install
{{- end }}
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: PrometheusRule
    plural: prometheusrules
  scope: Namespaced
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  version: v1
{{- else }}
  versions:
  - name: v1
    served: false
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
{{- end }}
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- else }}
apiVersion: apiextensions.k8s.io/v1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: {{ printf "servicemonitors.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  annotations:
    "helm.sh/hook": crd-install
{{- end }}
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: ServiceMonitor
    plural: servicemonitors
  scope: Namespaced
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  version: v1
{{- else }}
  versions:
  - name: v1
    served: false
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
{{- end }}
---
{{- end }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor") }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- else }}
apiVersion: apiextensions.k8s.io/v1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: {{ printf "podmonitors.%s" (.Values.operator.apiGroup | default "monitoring.coreos.com") }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  annotations:
    "helm.sh/hook": crd-install
{{- end }}
spec:
  group: {{ .Values.operator.apiGroup | default "monitoring.coreos.com" }}
  names:
    kind: PodMonitor
    plural: podmonitors
  scope: Namespaced
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1beta1" }}
  version: v1
{{- else }}
  versions:
  - name: v1
    served: false
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
{{- end }}
{{- end }}
{{- end -}}
