{{- if and (or .Values.storageSpec .Values.persistence.enabled) (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}
spec:
  {{- if .Values.storageSpec }}
{{ toYaml .Values.storageSpec | indent 2 }}
  {{- else }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessMode }}
  {{ if and .Values.persistence.storageClass (ne "default" .Values.persistence.storageClass) }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- end }}
{{- end -}}
